services:

  db_gitlab:
    image: mysql
    container_name: db_docker_gitlab
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev

  www_gitlab:
    build: php
    container_name: www_docker_gitlab
    ports:
      - "8085:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ../:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
